# utils/constants.py

# Time Settings
TICK_RATE = 1.0  # 1 real second = 1 simulation tick. (Lower this later to speed up time)
TICKS_PER_DAY = 24
SUNRISE_HOUR = 6   # 6:00 AM
SUNSET_HOUR = 18   # 6:00 P

# Map Settings
GRID_WIDTH = 100
GRID_HEIGHT = 100

# Survival Caps
MAX_THIRST = 100
MAX_HUNGER = 100
THIRST_THRESHOLD = 45  # When animals start looking for water
HUNGER_THRESHOLD = 40  # When animals start looking for food
CARNIVORE_HUNT_THRESHOLD = 70  # When carnivores start actively hunting

DESPERATION_THRESHOLD = 80  # When animals panic and break sleep cycles

# Reproduction Settings
REPRODUCTION_CHECK_INTERVAL = 24
REPRODUCTION_CHANCE = 0.18
REPRODUCTION_RADIUS = 8
REPRODUCTION_MIN_AGE_TICKS = 48
REPRODUCTION_COOLDOWN_TICKS = 72
REPRODUCTION_MAX_ANIMALS = 140
REPRODUCTION_MAX_BIRTHS_PER_TICK = 5
REPRODUCTION_MAX_THIRST = 55
REPRODUCTION_MAX_HUNGER = 55

# Poacher Event Settings
POACHER_EVENT_CHECK_INTERVAL = 12
POACHER_EVENT_CHANCE = 0.33
POACHER_MAX_ACTIVE = 2
POACHER_ZONE_SIZE = 25
POACHER_CAMP_THRESHOLD = 3
POACHER_CAMP_DURATION_TICKS = 72
POACHER_FLEE_RANGE = 8
POACHER_ARREST_RANGE = 1
POACHER_STEP = 1
POACHER_FLEE_STEP = 2
POACHER_POACH_TICKS = 2
